### ISSUE TITLE
Dose this package include the "IK-Switch Planner" mentioned in your paper?

### ISSUE THREAD

**Issue by FrankLin9981** [quangounet/bimanual#10]
Dear Coung,

Firstly, thanks a lot for the great work developed by your research team.
Recently, I also encounter the joint limits problem during dual arm manipulation.
I find your paper and this package on IEEE Xplore.

However, after I clone and install this repository, I try to execute the sample program.
In the program, it plans a trajectory well, but without regrasping in this case.
Thus, I try to modify the object goal pose to trigger the IK switch planner.
But it seems not work as expected.
So, I wonder if this package includes the "IK-Switch Planner".

Thank you again for this amazing work.

Sincerely, 
Frank

**Comment by quangounet** [comment]
@zhouxian can you comment on this?

**Comment by zhouxian** [comment]
Hi Frank,

I apologize in advance since it was developed 4 years ago so my memory sort of slipped away and I don't have the resources now to set up the env and test it now. What I could suggest is there's a branch called original-master, in which there are two files: `cc_planner_regrasp.py` and `cc_planner_regrasp_placement.py`. I guess the first file has the regrasp action implemented, and the second is a more complete planner with placement action, i.e. put the object on the table to seek support during regrasping.

Hope this helps.

**Comment by FrankLin9981** [comment]
@zhouxian @quangounet  Thanks for your reply.

I take a quick look at the original-master branch.
It looks helpful!
I'd try to mimic the demo program in this branch to test the regrasp action.
Thank you so much!
